// Copyright (c) 2014 Antony Arciuolo. See License.txt regarding use.
// Convenience "all headers" header for precompiled header files. Do NOT use 
// this to be lazy when including headers in .cpp files. Be explicit.
#pragma once
#ifndef oBase_all_h
#define oBase_all_h
#include <oBase/aabox.h>
#include <oBase/algorithm.h>
#include <oMemory/allocate.h>
#include <oBase/assert.h>
#include <oBase/color.h>
#include <oBase/colors.h>
#include <oBase/compression.h>
#include <oBase/concurrency.h>
#include <oBase/concurrent_linear_allocator.h>
#include <oBase/concurrent_queue.h>
#include <oBase/concurrent_queue_opt.h>
#include <oBase/countdown_latch.h>
#include <oBase/date.h>
#include <oBase/dec3n.h>
#include <oBase/enum_iterator.h>
#include <oBase/event.h>
#include <oBase/finally.h>
#include <oBase/fixed_string.h>
#include <oBase/fixed_vector.h>
#include <oBase/fourcc.h>
#include <oBase/guid.h>
#include <oBase/gzip.h>
#include <oBase/ini.h>
#include <oBase/input.h>
#include <oBase/intrusive_ptr.h>
#include <oBase/invalid.h>
#include <oBase/ip4.h>
#include <oBase/leak_tracker.h>
#include <oBase/linear_allocator.h>
#include <oBase/lock_free_queue.h>
#include <oBase/lzma.h>
#include <oBase/macros.h>
#include <oBase/moving_average.h>
#include <oBase/operators.h>
#include <oString/opttok.h>
#include <oBase/osc.h>
#include <oBase/path.h>
#include <oBase/path_traits.h>
#include <oBase/plane.h>
#include <oBase/rgb.h>
#include <oBase/sbb.h>
#include <oBase/sbb_allocator.h>
#include <oBase/scc.h>
#include <oBase/sphere.h>
#include <oBase/snappy.h>
#include <oBase/std_linear_allocator.h>
#include <oString/string.h>
#include <oString/string_traits.h>
#include <oBase/tagged_pointer.h>
#include <oBase/text_document.h>
#include <oBase/throw.h>
#include <oBase/threadpool.h>
#include <oBase/timer.h>
#include <oBase/tlsf_allocator.h>
#include <oBase/type_id.h>
#include <oBase/type_info.h>
#include <oBase/types.h>
#include <oBase/udec3.h>
#include <oBase/unordered_map.h>
#include <oBase/uri.h>
#include <oBase/xml.h>
#endif
